# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_teacher_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('s', '\u5c0f\u73ed'), ('m', '\u4e2d\u73ed'), ('l', '\u5927\u73ed')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
