# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_class_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('n', '\u7537'), ('v', '\u5973')], max_length=4, verbose_name='\u6027\u522b'),
        ),
    ]
