# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20161009_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u9886\u57df')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='\u7f16\u53f7')),
                ('name', models.TextField(verbose_name='\u5185\u5bb9')),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7c7b\u578b')),
                ('test', models.CharField(max_length=20, verbose_name='\u6d4b\u8bd5')),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Type'),
        ),
    ]
