# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20161014_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birth_Date',
            field=models.DateTimeField(verbose_name='\u51fa\u751f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='birth_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testing',
            name='test_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testing',
            name='test_start',
            field=models.DateTimeField(),
        ),
    ]
